package es.unex.giiis.medicinex

abstract class CatalogueProvider
{
    companion object
    {
        var categories : List<String> = listOf(
            "ADHESIVO TISULAR",
            "APÓSITO",
            "BARNIZ DE UÑAS",
            "CAPSULA",
            "CAPSULA LIBERACION MODIFICADA",
            "CHAMPU",
            "CHICLE",
            "COLIRIO",
            "COLIRIO DE LIBERACION PROLONGADA",
            "COMPRIMIDO",
            "COMPRIMIDO BUCAL/PARA CHUPAR",
            "COMPRIMIDO BUCODISPERSABLE/LIOTAB",
            "COMPRIMIDO EFERVESCENTE",
            "COMPRIMIDO LIBERACION MODIFICADA",
            "COMPRIMIDO MASTICABLE",
            "COMPRIMIDO SUBLINGUAL",
            "CONSERVACION ORGANOS",
            "CREMA",
            "DIALISIS PERITONEAL",
            "DISPOSITIVO INTRAUTERINO",
            "DISPOSITIVO VAGINAL",
            "EMULSION",
            "EQUIVALENTE DE TEJIDO VIVO",
            "GEL",
            "GEL ENDOCERVICAL",
            "GEL INTESTINAL",
            "GEL INTRAUTERINO",
            "GEL OFTALMICO",
            "HEMOFILTRACION",
            "IMPLANTE",
            "IMPLANTE OFTALMICO",
            "INHALACION ENDOTRAQUEOPULMONAR",
            "INHALACIÓN PULMONAR",
            "INYECTABLE",
            "INYECTABLE PERFUSION",
            "LIQUIDO GASTROENTERICO",
            "LIQUIDO RECTAL",
            "LIQUIDO USO TOPICO",
            "LIQUIDO VAGINAL",
            "LIQUIDO OTICO",
            "OVULO/CAPSULA/COMPRIMIDO VAGINAL",
            "PARCHE TRANSDERMICO",
            "PASTA",
            "POLVO/GRANULADO LIBERACION MODIFICADA",
            "POMADA",
            "POMADA OFTALMICA",
            "PREPARADO IRRIGACION VESICAL",
            "PREPARADO URETRAL",
            "PRODUCTO PARA EL BAÑO",
            "PRODUCTO USO BUCAL TOPICO",
            "PRODUCTO USO NASAL",
            "PRUEBA ALERGIA",
            "PULVERIZACION BUCAL",
            "PULVERIZACION SUBLINGUAL",
            "RADIOFARMACO",
            "SEMISOLIDO RECTAL",
            "SEMISOLIDO VAGINAL",
            "SOLIDO USO TOPICO",
            "SOLUCION/SUSPENSION GOTAS ORALES",
            "SOLUCIÓN/SUSPENSIÓN ORAL",
            "SOLUCIÓN/SUSPENSIÓN ORAL EFERVESCENTE",
            "SOLUCIÓN PARA MODIFICACIÓN DE LAS FRACCIONES SANGUÍNEAS",
            "SOLUCIÓN TRANSDÉRMICA",
            "SUPOSITORIO"
        )
    }
}